# .github/workflows/deploy.yml
name: Deploy to EC2 with Self-Hosted Runner

on:
  push:
    branches:
      - main # mainブランチにプッシュされた時にデプロイを実行

jobs:
  deploy:
    name: Build and Deploy on EC2
    # 実行マシンとして、あなたが設定した自己ホストランナーを指定します
    runs-on: self-hosted

    steps:
      # ステップ1: EC2サーバー（ランナーが動いている場所）の作業ディレクトリに、
      # リポジトリの最新コードをダウンロードします。
      - name: Checkout code
        uses: actions/checkout@v4

      # ステップ2: デプロイ用のコマンドをEC2サーバー上で直接実行します。
      # (SSH接続が不要になり、よりシンプルになります)
      - name: Deploy Application
        run: |
          echo "デプロイを開始します..."

          # Goバックエンドのビルドと再起動
          # ランナーの作業ディレクトリからの相対パスで指定します
          echo "バックエンドを更新中..."
          cd backend
          pkill -f 'main' || true  # 実行中の古いサーバーがあれば停止
          go build -o main .       # Goアプリをビルド
          nohup ./main > backend.log 2>&1 & # 新しいサーバーをバックグラウンドで起動
          cd ..

          # Reactフロントエンドのビルド
          echo "フロントエンドをビルド中..."
          cd frontend/calculator-ui
          npm install
          npm run build
          cd ../..

          # ビルドしたReactファイルをNginxの公開ディレクトリにコピー
          echo "フロントエンドのファイルを配置中..."
          sudo cp -r frontend/calculator-ui/build/* /usr/share/nginx/html/

          echo "デプロイが完了しました！"